# Generated by Django 4.2.5 on 2023-09-24 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="people",
            name="b_date",
            field=models.DateTimeField(default=None, verbose_name="birthday"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="people",
            name="d_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="death day"),
        ),
        migrations.AddField(
            model_name="people",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMAL", "Female"), ("UNKNOW", "Unkonw")],
                default="UNKNOW",
                max_length=10,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="people",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r_children",
                to="app.people",
                verbose_name="mother",
            ),
        ),
        migrations.AlterField(
            model_name="people",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="l_children",
                to="app.people",
                verbose_name="father",
            ),
        ),
        migrations.AlterField(
            model_name="people",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
