# Generated by Django 4.2.5 on 2023-09-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_event_people_b_date_people_d_date_people_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="b_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="birthday"),
        ),
    ]
