# Generated by Django 4.2.5 on 2024-01-29 08:54

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('app', '0003_alter_people_b_date'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='people',
#            name='brief',
#            field=models.TextField(blank=True, null=True, verbose_name='简介'),
#        ),
        migrations.AddField(
            model_name='relationship',
            name='fro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_from', to='app.people', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_to', to='app.people', verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='name',
            field=models.CharField(max_length=20, verbose_name='关系'),
        ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='app.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='people',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='app.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
