# Generated by Django 4.2.5 on 2024-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_people_brief_relationship_fro_relationship_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='brief',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
