# Generated by Django 4.2.5 on 2024-01-29 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0005_people_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='fro',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to',
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_from', to='contenttypes.contenttype', verbose_name='from'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_to', to='contenttypes.contenttype', verbose_name='to'),
        ),
    ]
